on: [push, pull_request]

name: CI

jobs:

  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.1 # STABLE
          - 1.46.0 # MSRV
        features:
          - default
          - electrum
          - esplora-ureq
          - esplora-reqwest
          - compiler
          - compact_filters
          - reserves
          - reserves,electrum
          - reserves,esplora-ureq
          - reserves,compact_filters
          - reserves,rpc
          - rpc
          - electrum,verify
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate cache key
        run: echo "${{ matrix.rust }} ${{ matrix.features }}" | tee .cache_key
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('.cache_key') }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Build
        run: cargo build --features ${{ matrix.features }} --locked
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --features ${{ matrix.features }}

  fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Check fmt
        run: cargo fmt --all -- --check
